name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, params: "'-PtestedGradleVersion=6.9.4|7.6.3|8.10.2' pnpmTests" }
          - {os: ubuntu-latest, params: "'-PtestedGradleVersion=6.9.4|7.6.3|8.10.2' build" }
          - {os: windows-latest, params: "build pnpmTests" }
          - {os: macos-latest, params: "build pnpmTests" }
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - name: Build
        run: ./gradlew --scan "-Pcom.github.gradle.node.predictivetestselection=${{ github.event_name == 'pull_request' }}" ${{ matrix.config.params }}
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
